### ISSUE TITLE
socket code does not compile on visual studio

### ISSUE THREAD

**Issue by devrantt** [tezc/sc#37]
socket test runs but when I try myself it doesn't compile, visual studio shows many errors.

**Comment by tezc** [comment]
Can I try it? Could you post an example?

I assume you mean socket_test.c runs fine, if so, you need to initialize sockets by calling : [WSAStartup](https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-wsastartup)

I do that for that test here : https://github.com/tezc/sc/blob/1d40f0b0eaeb28d3e6fcded669c18705638c9bc7/socket/sock_test.c#L1474

I didn't add that auto initialization to the library, because library can't know if you called it before, so, rather than dealing multiple initializations, it's up to library users on Windows. 

Anyway, I'll add an example for sockets in a few days hopefully.

**Comment by devrantt** [comment]
WSAStartup/WSACleanup worked , thank you very much.

**Comment by tezc** [comment]
@devrantt 

Merged sock_startup() and sock_cleanup(), it will initialize on socket api on windows, other OS'es it will be noop.

https://github.com/tezc/sc/blob/9db998bad4e7ae80b8d2d4d7e74d5bf90c4062cf/socket/sc_sock.h#L99
