### ISSUE TITLE
Compile errors on Release

### ISSUE THREAD

**Issue by rafaeldelboni** [tezc/sc#44]
I'm having some errors when compiling this project as Release:
# Steps to reproduce
```bash
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j
```
# Errors log:
[stderr.txt](https://github.com/tezc/sc/files/5984397/stderr.txt)

I would like to give the credit to @lucascebertin that point out this "bug"

**Comment by rafaeldelboni** [comment]
If I change these lines
`if (NOT CMAKE_C_COMPILER_ID MATCHES "MSVC")`

To this:
`if (NOT CMAKE_C_COMPILER_ID MATCHES "MSVC" AND SC_BUILD_TEST)`

I can disable this behavior from my build, but this is a good solution?

**Comment by tezc** [comment]
We shouldn't build tests in release mode because libs won't be testable thoroughly without some tricks compiler provides in debug mode. e.g testing return value of malloc, system calls etc.

How about something like this : https://github.com/tezc/sc/pull/45/files. 
Here we build tests only on Debug build. 

I didn't expect anybody use my messy cmakefiles, all started from it, sorry about that :)
We have some tests for release mode actually that we use in our projects but I need to clean them up and then merge to this repo. It may take some time though.

**Comment by rafaeldelboni** [comment]
Thanks for the super-duper fast response and sorry for not making the intended use of your repo! :grimacing: 

Is looking good, just made a comment about a still going warning on `sc_thread.c`, besides that, is looking good!

**Comment by tezc** [comment]
I should've written "closes" I guess :)

**Comment by rafaeldelboni** [comment]
> I should've written "closes" I guess :)

Yes or you could set `Linked pull requests` in the menu on the right :robot:

**Comment by rafaeldelboni** [comment]
Mind making a new release?

**Comment by tezc** [comment]
Done : https://github.com/tezc/sc/releases/tag/v1.0.1
